[package]
name = "dol_symbol_table_macro"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
phf = { version = "0.8", default-features = false }

[build-dependencies]
phf_codegen = "0.8"
