[package]
name = "rel_loader"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primeapi = { path = "../primeapi-rs" }

[lib]
crate-type = ["staticlib"]
