[package]
name = "resource_info_table_macro"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
phf = { version = "0.8", default-features = false }
proc-macro2 = "1"
syn = "1"

[build-dependencies]
phf_codegen = "0.8"
