[package]
name = "nod_wrapper"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[dependencies]
cpp = "0.5"
reader_writer = { path = "../reader_writer" }

[build-dependencies]
# cmake = "0.1"
cpp_build = "0.5"
cc = "1.0"
