[package]
name = "ppcasm"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2018"

[dependencies]
ppcasm_macro = { path = "ppcasm_macro" }
byteorder = "1.*"
generic-array = "0.14"

[[test]]
name = "test_ppcasm"
path = "tests/test.rs"
